export enum AdminEmailEvent {
  CREATE_ACCOUNT_EVENT = 'CREATE_ACCOUNT_EVENT',
  RESET_PASSWORD_SUCCESSFUL = 'RESET_PASSWORD_SUCCESSFUL',
  FORGET_PASSWORD = 'FORGET_PASSWORD',
  OTP_VERIFICATION = 'OTP_VERIFICATION',
  SEND_OTP = 'SEND_OTP',
}
